# Generated by Django 5.2.3 on 2026-04-01 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('avg_price', models.DecimalField(decimal_places=10, max_digits=28)),
                ('balance', models.DecimalField(decimal_places=10, max_digits=28)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Holdings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(fields=('user', 'symbol'), name='uniq_holding_user_symbol'),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('rewards', 'Rewards')], default='buy', max_length=16)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=28)),
                ('price', models.DecimalField(decimal_places=10, max_digits=28)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='spot.holding')),
            ],
            options={
                'verbose_name_plural': 'Records',
                'ordering': ['-date'],
            },
        ),
    ]
