# Generated by Django 5.2.3 on 2026-03-29 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=10, max_digits=28)),
                ('price', models.DecimalField(decimal_places=10, max_digits=28)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='spot.holding')),
            ],
            options={
                'verbose_name_plural': 'Records',
                'ordering': ['-date'],
            },
        ),
    ]
